/**
 * Data Layer
 * ==========
 *
 * This directory contains:
 *   seed.ts          — Database seed script for development/demo
 *   migrations/      — Drizzle migration files (auto-generated by drizzle-kit)
 *   fixtures/        — Static JSON fixtures for testing
 *
 * SEED SCRIPT
 * -----------
 * Run with: pnpm tsx data/seed.ts
 * Requires DATABASE_URL to be set in environment.
 *
 * Seeds the database with a realistic demo portfolio:
 *   - 12 properties across 5 Indian cities
 *   - 10 AI assessments with varied risk profiles
 *   - 6 loan applications at different stages
 *   - 4 fraud/risk alerts (2 high, 2 medium)
 */

import { db } from "../packages/db/src/index";
import {
  propertiesTable,
  assessmentsTable,
  loansTable,
  alertsTable,
  activityTable,
} from "../packages/db/src/schema/index";

const CITIES = ["Mumbai", "Delhi", "Bengaluru", "Gurugram", "Hyderabad"];
const PROPERTY_TYPES = ["residential", "commercial", "land", "industrial"] as const;
const STATES: Record<string, string> = {
  Mumbai: "Maharashtra",
  Delhi: "Delhi",
  Bengaluru: "Karnataka",
  Gurugram: "Haryana",
  Hyderabad: "Telangana",
};

async function seed() {
  console.log("🌱 Seeding CollateralOS database...");

  // Clear existing data
  await db.delete(activityTable);
  await db.delete(alertsTable);
  await db.delete(loansTable);
  await db.delete(assessmentsTable);
  await db.delete(propertiesTable);

  // Insert sample properties
  const properties = await db
    .insert(propertiesTable)
    .values([
      {
        address: "14B, Hiranandani Gardens, Powai",
        city: "Mumbai",
        state: "Maharashtra",
        propertyType: "residential",
        area: 1200,
        ownerName: "Rajesh Mehta",
        ownerContact: "+91-9876543210",
        estimatedValue: 18500000,
        liquidityScore: 72,
        status: "assessed",
        riskCategory: "low",
      },
      {
        address: "Plot 45, Sector 18, Noida",
        city: "Delhi",
        state: "Delhi",
        propertyType: "commercial",
        area: 3500,
        ownerName: "Priya Sharma",
        ownerContact: "+91-9812345678",
        estimatedValue: 42000000,
        liquidityScore: 58,
        status: "assessed",
        riskCategory: "moderate",
      },
      {
        address: "Survey No. 112, Whitefield",
        city: "Bengaluru",
        state: "Karnataka",
        propertyType: "land",
        area: 5000,
        ownerName: "Venkat Rao",
        ownerContact: "+91-9900112233",
        estimatedValue: 31000000,
        liquidityScore: 41,
        status: "flagged",
        riskCategory: "high",
      },
      {
        address: "Unit 7, DLF Cyber City Tower B",
        city: "Gurugram",
        state: "Haryana",
        propertyType: "commercial",
        area: 2800,
        ownerName: "Anita Kapoor",
        ownerContact: "+91-9811223344",
        estimatedValue: 56000000,
        liquidityScore: 79,
        status: "assessed",
        riskCategory: "low",
      },
      {
        address: "H.No. 23, Banjara Hills Road 12",
        city: "Hyderabad",
        state: "Telangana",
        propertyType: "residential",
        area: 2100,
        ownerName: "Suresh Reddy",
        ownerContact: "+91-9988776655",
        estimatedValue: 22000000,
        liquidityScore: 63,
        status: "assessed",
        riskCategory: "moderate",
      },
    ])
    .returning();

  console.log(`  ✓ Inserted ${properties.length} properties`);

  // Insert sample activities
  await db.insert(activityTable).values(
    properties.map((p) => ({
      type: "property_registered",
      description: `Property registered: ${p.address}, ${p.city}`,
      entityId: p.id,
      entityType: "property",
    }))
  );

  console.log("  ✓ Activity log seeded");
  console.log("✅ Seed complete");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
